name: Docker Image CI

on: 
  workflow_dispatch:
jobs:
 main:
   runs-on: ubuntu-latest
   steps:
     -
       name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     -     
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
     -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         push: true
         tags: |
          ghcr.io/neugartf/mautrix-telegram:latest
          ghcr.io/neugartf/mautrix-telegram:v0.9.0    
         platforms: linux/arm/v7
