name: Docker Image CI

on: 
  workflow_dispatch:

jobs:
 main:
   runs-on: ubuntu-latest
   steps:
     -
       name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         push: true
         tags: neugartf/mautrix-telegram:latest
         platforms: linux/arm/v6,linux/arm/v7 
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GHCR }}
